image: google/cloud-sdk
definitions:
  services:
    docker:
      memory: 2048
options:
  docker: true
pipelines:
  branches:
    master:
      - step:
          name: Build and push docker image
          size: 2x
          services:
            - docker
          caches:
            - docker
          script:
            - echo ${KEY_FILE_PRD_US_CENTRAL} | base64 -d >> /tmp/key-file.json
            - gcloud auth activate-service-account --key-file /tmp/key-file.json --quiet
            - gcloud config set project volanty
            - gcloud auth configure-docker --quiet
            - docker build -t volanty/quanto-vale-o-meu-carro:${BITBUCKET_COMMIT} .
            - 'docker tag volanty/quanto-vale-o-meu-carro:${BITBUCKET_COMMIT} us.gcr.io/volanty/quanto-vale-o-meu-carro:${BITBUCKET_COMMIT}'
            - 'docker push us.gcr.io/volanty/quanto-vale-o-meu-carro:${BITBUCKET_COMMIT}'
      - step:
          name: Deploy to hml
          deployment: staging # can be test, staging or production.
          script:
            - echo ${KEY_FILE_HML} | base64 -d >> /tmp/key-file.json
            - gcloud auth activate-service-account --key-file /tmp/key-file.json --quiet
            - gcloud config set project volanty-hml
            - gcloud container clusters get-credentials elasticsearch-cluster --zone us-central1-a --project volanty-hml
            - kubectl apply -f k8s/configmap-hml.yaml
            - cat k8s/deployment.yaml | sed "s/latest/$BITBUCKET_COMMIT/g" | kubectl apply -f -
            - kubectl apply -f k8s/service.yaml
            - kubectl apply -f k8s/ingress.yaml
            - kubectl apply -f k8s/mapping.yaml
            - kubectl apply -f k8s/certificate.yaml
            - kubectl apply -f k8s/tls-context.yaml
      - step:
          name: Deploy to production
          trigger: manual
          deployment: production # can be test, staging or production.
          script:
            - echo ${KEY_FILE_PRD_US_CENTRAL} | base64 -d >> /tmp/key-file.json
            - gcloud auth activate-service-account --key-file /tmp/key-file.json --quiet
            - gcloud config set project volanty
            - gcloud container clusters get-credentials elasticsearch-cluster --zone us-central1-a --project volanty
            - kubectl apply -f k8s/configmap-prd.yaml
            - 'cat k8s/deployment.yaml | sed -e "s/latest/$BITBUCKET_COMMIT/g" -e "s/replicas: 1/replicas: 3/g" | kubectl apply -f -'
            - kubectl apply -f k8s/service.yaml
            - kubectl apply -f k8s/ingress.yaml
            - kubectl apply -f k8s/mapping.yaml
            - 'cat k8s/certificate.yaml | sed -e "s/letsencrypt-dev/letsencrypt-prod/g" | kubectl apply -f -'
            - kubectl apply -f k8s/tls-context.yaml